# Generated by Django 3.2.7 on 2021-09-24 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('body', models.TextField(max_length=500, verbose_name='Текст статьи')),
                ('author', models.CharField(max_length=50, verbose_name='Автор статьи')),
                ('time_post', models.DateTimeField(auto_now=True, verbose_name='Дата публикации статьи')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('author', models.CharField(max_length=50, verbose_name='Автор комментария')),
                ('time_post', models.DateTimeField(auto_now=True, verbose_name='Дата публикации комментария')),
                ('fk_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.post')),
            ],
        ),
    ]
