# Generated by Django 3.2.7 on 2021-11-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211019_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameTag', models.TextField(max_length=500, verbose_name='Текст тега')),
                ('courses', models.ManyToManyField(to='news.Post')),
            ],
        ),
    ]
