# Generated by Django 3.2.7 on 2021-11-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='courses',
        ),
        migrations.AddField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(to='news.Tag'),
        ),
    ]
