# Generated by Django 3.2.7 on 2021-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20211110_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='posts', to='news.Tag'),
        ),
    ]
