# Generated by Django 3.2.7 on 2021-11-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20211122_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='posts', to='news.Tag'),
        ),
    ]
