# Generated by Django 3.2.7 on 2022-02-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20211122_1833'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': (('can_see_author', 'Можно видеть автора комментария.'),), 'verbose_name': 'Коммантарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
